# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_create_room_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='song',
        ),
        migrations.AddField(
            model_name='entry',
            name='game',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='room.Game'),
            preserve_default=False,
        ),
    ]
