# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 08:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0002_modify_game_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='players',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
