# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_create_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='guessed',
            field=models.BooleanField(default=False),
        ),
    ]
