# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0001_initialize_lyrics_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyricsword',
            old_name='lyric_position',
            new_name='position',
        ),
    ]
