# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0002_rename_lyrics_position_to_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='lyrics',
        ),
    ]
