# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0003_remove_song_lyrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='player',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='song',
        ),
        migrations.RemoveField(
            model_name='game',
            name='room',
        ),
        migrations.RemoveField(
            model_name='game',
            name='song',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
